name: CI Workflow week5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests
      run: |
        pytest test_app.py


          - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v3
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      aws-region: us-east-1

    - name: Log in to Amazon ECR
    run: |
      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 027308965840.dkr.ecr.us-east-1.amazonaws.com

     -name: Push Docker Image to Amazon ECR
    run: |
      docker tag flask-ci:latest 027308965840.dkr.ecr.us-east-1.amazonaws.com/flask-ci:latest
      docker push 027308965840.dkr.ecr.us-east-1.amazonaws.com/flask-ci:latest