name: Build and Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - main  # Runs this workflow when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (optional but recommended)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to AWS ECR using AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # Step 4: Log in to Amazon ECR using Docker
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 027308965840.dkr.ecr.us-east-1.amazonaws.com

    # Step 5: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t my-app:latest .

    # Step 6: Tag Docker image with ECR repository URI
    - name: Tag Docker Image
      run: |
        docker tag my-app:latest 027308965840.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

    # Step 7: Push the Docker image to Amazon ECR
    - name: Push Docker Image to Amazon ECR
      run: |
        docker push 027308965840.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
